### ISSUE TITLE
Plugin is enabled for all projects in a multi project build

### ISSUE THREAD

**Issue by MasseGuillaume** [databricks/sbt-databricks#2]
We only want to use this plugin for a subset of our projects.
https://github.com/databricks/sbt-databricks/blob/master/src/main/scala/sbtdatabricks/DatabricksPlugin.scala#L33

**Comment by brkyvz** [comment]
Hi,
You may disable the plugin for the other subset as described [here](http://www.scala-sbt.org/0.13/docs/Plugins.html#Using+an+auto+plugin).
Basically by adding the setting `.disablePlugins(DatabricksPlugin)`

Please let me know if you have any problems!
Burak

**Comment by MasseGuillaume** [comment]
More or less. We have N projects and 1 or 2 Spark projects. We would have to append this to N-1 projects.

This guys has the same issue: http://stackoverflow.com/questions/25425357/how-can-i-disable-an-sbt-plugin-for-all-projects-globally

**Comment by marmbrus** [comment]
Hey, thanks for the feedback.  What exactly is the problem with it adding itself to all of your projects?  Is it that when you just do deploy in the root project it uploads more than you want?  Would it work for your use case to create an aggregate project with only the spark projects and then deploy just that?

Also, I'm not sure if this works, but have you tried using `disablePlugins` on the root project?

**Comment by xavierclements** [comment]
@marmbrus jumping in @MasseGuillaume. I have disabled plugins in my build and then re-enabled them for particular projects. It uploads WAY more than I want because it will upload dependent libraries for each 

Wider question: Is there any thought to adding in parameters so that clusters, projects, individual libraries etc can be passed in. 

Further I have a PR open that adds in context and command functionality but it suffers from the same problem of running for each active project. Can you separate out the hard link to projects in some way? Not sure how.

**Comment by brkyvz** [comment]
Hi @xavierclements 
You can deploy a single project (and it's dependencies) by calling `sbt project-a/dbcDeploy`. Doesn't that solve your problem? The same methodology can be used for any sbt command: `project-a/package`, `project-b/package`, `project-c/dbcUpload`...
Right now, doing this unfortunately doesn't upload project-a, if project-b depends on project-a, but the fix is included in my PR.
Regarding supplying parameters, we can add that functionality. Our initial thought was that `clusters` would be pretty much static. We can add options to override them, if they are passed as a parameter.

**Comment by xavierclements** [comment]
@brkyvz thanks. my sbt infancy shining through there. That project/dbcExecuteCommand also worked for the functionality in my [PR#7](https://github.com/databricks/sbt-databricks/pull/7). Much obliged.

Which PR is it that fixes the dependsOn packaging?

We definitely need the option to override clusters as we have multiple users developing and deploying to separate clusters. What would be the time line on this?

**Comment by marmbrus** [comment]
@xavierclements, I've been considering suggesting that users configure this plugin using the [sbt global configuration](http://www.scala-sbt.org/0.13/docs/Global-Settings.html) instead of baking it into the build.  This way it would be fine to hard code your password in (assuming you have safe home directory permissions) and you could specify per user things like which cluster to deploy to easily.  Would that work for you?

**Comment by xavierclements** [comment]
@marmbrus for the password etc the global configuration sounds good. but having the flexibility to pass in the cluster name as a parameter would be very useful (not sure if that's what you were getting at?)

**Comment by marmbrus** [comment]
@xavierclements, I was wondering if per-user configuration of the cluster to upload to was sufficient for your use case.

I'll add you can also dynamically change the configuration (this is my workflow when using the plug-in).

From the sbt console:
```
> set dbcClusters in datasources := "michael"
> datasources/dbcDeploy
...
```

From the commandline:

```
sbt 'set dbcClusters in datasources := "michael"' datasources/dbcDeploy
```

I'm not super opposed to adding an option to deploy, but would like to understand what you are looking for better.  If it works for you, I think it would be better to stick with existing sbt configuration mechanisms rather than adding multiple paths for specifying which cluster to deploy to.

**Comment by xavierclements** [comment]
@marmbrus this is a sbt schoolin' I tells ya!! That sbt command line call completely solves my issue with deployment to a specific cluster and also setting the path to a command file. 

As for your comment regarding 'sbt global configuration', I'm not that familiar but if it could help with setting up the credentials aspect of the connection that would be helpful.

**Comment by marmbrus** [comment]
Awesome :)

We'll update our documentation to include more "intro to sbt" type stuff.

**Comment by xavierclements** [comment]
much obliged.

**Comment by brkyvz** [comment]
Severity decreased with PR #10. I'll update documentation with sbt-tips
